### ISSUE TITLE
Unclear of intended use of this repo

### ISSUE THREAD

**Issue by paddotk** [OfficeDev/microsoft-teams-sample-auth-node#25]
Something is not clear for me, reading the readme/wiki of this repository. The description up top is `"Sample illustrating seamless inline authentication for Microsoft Teams apps."` whereas the description of [this repo](https://github.com/OfficeDev/microsoft-teams-sample-complete-node) says `"A template for building complex bots for Microsoft Teams - Node.JS version"`. Yet when on this repo (sample-auth-node) I read on, it shows instructions for setting up a bot.

What gives? Which repo is the authentication Javascript SDK?

**Comment by aosolis** [comment]
Hi, this repo shows authentication for tabs and bots in Teams. It has samples for using the [Teams Javascript SDK](https://github.com/OfficeDev/microsoft-teams-library-js) and [ADAL JS](https://github.com/AzureAD/azure-activedirectory-library-for-js). 

We're in the process of adding samples for [MSAL JS](https://github.com/AzureAD/microsoft-authentication-library-for-js) and [tab SSO](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso).
